-- =========================================================
-- SISTEM PEMBELIAN DAN PENGENDALIAN ANGGARAN
-- BAHAN HABIS PAKAI PADA USAHA SALON
-- Database : PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. HAPUS TABEL LAMA JIKA ADA
-- =========================================================

DROP TABLE IF EXISTS public.pembelian CASCADE;
DROP TABLE IF EXISTS public.anggaran CASCADE;
DROP TABLE IF EXISTS public.bahan CASCADE;


-- =========================================================
-- 2. TABEL BAHAN
-- =========================================================

CREATE TABLE public.bahan (
    id_bahan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nama_bahan TEXT NOT NULL,

    satuan TEXT NOT NULL,

    stok_minimum NUMERIC(12,2)
        NOT NULL
        DEFAULT 0
        CHECK (stok_minimum >= 0),

    status_aktif BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW()
);


-- =========================================================
-- 3. TABEL ANGGARAN
-- =========================================================

CREATE TABLE public.anggaran (
    id_anggaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_bahan BIGINT NOT NULL,

    periode DATE NOT NULL,

    nominal_anggaran NUMERIC(14,2)
        NOT NULL
        CHECK (nominal_anggaran >= 0),

    keterangan TEXT,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    CONSTRAINT fk_anggaran_bahan
        FOREIGN KEY (id_bahan)
        REFERENCES public.bahan(id_bahan)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT unique_anggaran_bahan_periode
        UNIQUE (id_bahan, periode)
);


-- =========================================================
-- 4. TABEL PEMBELIAN
-- =========================================================

CREATE TABLE public.pembelian (
    id_pembelian BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_bahan BIGINT NOT NULL,

    tanggal DATE
        NOT NULL
        DEFAULT CURRENT_DATE,

    supplier TEXT,

    qty NUMERIC(12,2)
        NOT NULL
        CHECK (qty > 0),

    harga_satuan NUMERIC(14,2)
        NOT NULL
        CHECK (harga_satuan >= 0),

    total_harga NUMERIC(14,2)
        GENERATED ALWAYS AS (qty * harga_satuan) STORED,

    keterangan TEXT,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    CONSTRAINT fk_pembelian_bahan
        FOREIGN KEY (id_bahan)
        REFERENCES public.bahan(id_bahan)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- =========================================================
-- 5. INDEX
-- =========================================================

CREATE INDEX idx_anggaran_id_bahan
ON public.anggaran(id_bahan);

CREATE INDEX idx_anggaran_periode
ON public.anggaran(periode);

CREATE INDEX idx_pembelian_id_bahan
ON public.pembelian(id_bahan);

CREATE INDEX idx_pembelian_tanggal
ON public.pembelian(tanggal);


-- =========================================================
-- 6. ROW LEVEL SECURITY (RLS)
-- =========================================================

ALTER TABLE public.bahan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anggaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pembelian ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 7. HAK AKSES UNTUK APLIKASI
-- =========================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.bahan
TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.anggaran
TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.pembelian
TO anon, authenticated;


-- Hak menggunakan sequence ID
GRANT USAGE, SELECT
ON SEQUENCE public.bahan_id_bahan_seq
TO anon, authenticated;

GRANT USAGE, SELECT
ON SEQUENCE public.anggaran_id_anggaran_seq
TO anon, authenticated;

GRANT USAGE, SELECT
ON SEQUENCE public.pembelian_id_pembelian_seq
TO anon, authenticated;


-- =========================================================
-- 8. RLS POLICY - BAHAN
-- =========================================================

CREATE POLICY "bahan_select"
ON public.bahan
FOR SELECT
TO anon, authenticated
USING (TRUE);

CREATE POLICY "bahan_insert"
ON public.bahan
FOR INSERT
TO anon, authenticated
WITH CHECK (TRUE);

CREATE POLICY "bahan_update"
ON public.bahan
FOR UPDATE
TO anon, authenticated
USING (TRUE)
WITH CHECK (TRUE);

CREATE POLICY "bahan_delete"
ON public.bahan
FOR DELETE
TO anon, authenticated
USING (TRUE);


-- =========================================================
-- 9. RLS POLICY - ANGGARAN
-- =========================================================

CREATE POLICY "anggaran_select"
ON public.anggaran
FOR SELECT
TO anon, authenticated
USING (TRUE);

CREATE POLICY "anggaran_insert"
ON public.anggaran
FOR INSERT
TO anon, authenticated
WITH CHECK (TRUE);

CREATE POLICY "anggaran_update"
ON public.anggaran
FOR UPDATE
TO anon, authenticated
USING (TRUE)
WITH CHECK (TRUE);

CREATE POLICY "anggaran_delete"
ON public.anggaran
FOR DELETE
TO anon, authenticated
USING (TRUE);


-- =========================================================
-- 10. RLS POLICY - PEMBELIAN
-- =========================================================

CREATE POLICY "pembelian_select"
ON public.pembelian
FOR SELECT
TO anon, authenticated
USING (TRUE);

CREATE POLICY "pembelian_insert"
ON public.pembelian
FOR INSERT
TO anon, authenticated
WITH CHECK (TRUE);

CREATE POLICY "pembelian_update"
ON public.pembelian
FOR UPDATE
TO anon, authenticated
USING (TRUE)
WITH CHECK (TRUE);

CREATE POLICY "pembelian_delete"
ON public.pembelian
FOR DELETE
TO anon, authenticated
USING (TRUE);


-- =========================================================
-- 11. DATA CONTOH
-- =========================================================

INSERT INTO public.bahan
    (nama_bahan, satuan, stok_minimum)
VALUES
    ('Shampoo', 'Botol', 5),
    ('Conditioner', 'Botol', 5),
    ('Hair Mask', 'Jar', 3),
    ('Cat Rambut', 'Tube', 5),
    ('Sarung Tangan', 'Box', 2);


-- =========================================================
-- SELESAI
-- =========================================================